teams = [
    "Anaheim Ducks",
    "Arizona Coyotes",
    "Boston Bruins",
    "Buffalo Sabres",
    "Calgary Flames",
    "Carolina Hurricanes",
    "Chicago Blackhawks",
    "Colorado Avalanche",
    "Columbus Blue Jackets",
    "Dallas Stars",
    "Detroit Red Wings",
    "Edmonton Oilers",
    "Florida Panthers",
    "Los Angeles Kings",
    "Minnesota Wild",
    "Montreal Canadiens",
    "Nashville Predators",
    "New Jersey Devils",
    "New York Islanders",
    "New York Rangers",
    "Ottawa Senators",
    "Philadelphia Flyers",
    "Pittsburgh Penguins",
    "San Jose Sharks",
    "St. Louis Blues",
    "Tampa Bay Lightning",
    "Toronto Maple Leafs",
    "Vancouver Canucks",
    "Vegas Golden Knights",
    "Washington Capitals",
    "Winnipeg Jets",
]

# default names from pd.read_html on nhl
"""to_fix = {'201810030TOR_scoring': [('1st Period', '09:34'),
                          ('1st Period.1', 'MTL'),
                          ('1st Period.2', nan),
                          ('1st Period.3', 'Artturi Lehkonen  (1)'),
                          ('1st Period.4', 'Max Domi  ,  Paul Byron')],
 '201810030TOR_penalty': [('1st Period', '11:02'),
                          ('1st Period.1', 'MTL'),
                          ('1st Period.2', 'Jonathan Drouin'),
                          ('1st Period.3', 'Hooking'),
                          ('1st Period.4', '2 min')],
 '201810030TOR_MTL_skaters': [(('Unnamed: 0_level_0', 'Rk'), 1.0),
                              (('Unnamed: 1_level_0', 'Player'), 'Joel Armia'),
                              (('Scoring', 'G'), 0),
                              (('Scoring', 'A'), 0),
                              (('Scoring', 'PTS'), 0),
                              (('Unnamed: 5_level_0', '+/-'), 0.0),
                              (('Unnamed: 6_level_0', 'PIM'), 0),
                              (('Goals', 'EV'), 0),
                              (('Goals', 'PP'), 0),
                              (('Goals', 'SH'), 0),
                              (('Goals', 'GW'), 0.0),
                              (('Assists', 'EV'), 0.0),
                              (('Assists', 'PP'), 0.0),
                              (('Assists', 'SH'), 0.0),
                              (('Unnamed: 14_level_0', 'S'), 4),
                              (('Unnamed: 15_level_0', 'S%'), 0.0),
                              (('Unnamed: 16_level_0', 'SHFT'), 25.0),
                              (('Unnamed: 17_level_0', 'TOI'), '18:50')],
 '201810030TOR_MTL_goalies': [(('Unnamed: 0_level_0', 'Rk'), 1),
                              (('Unnamed: 1_level_0', 'Player'), 'Carey Price'),
                              (('Unnamed: 2_level_0', 'DEC'), 'O'),
                              (('Goalie Stats', 'GA'), 3),
                              (('Goalie Stats', 'SA'), 26),
                              (('Goalie Stats', 'SV'), 23),
                              (('Goalie Stats', 'SV%'), 0.885),
                              (('Goalie Stats', 'SO'), 0),
                              (('Unnamed: 8_level_0', 'PIM'), 0),
                              (('Unnamed: 9_level_0', 'TOI'), '61:01')],
 '201810030TOR_TOR_skaters': [(('Unnamed: 0_level_0', 'Rk'), 1.0),
                              (('Unnamed: 1_level_0', 'Player'), 'Connor Brown'),
                              (('Scoring', 'G'), 0),
                              (('Scoring', 'A'), 0),
                              (('Scoring', 'PTS'), 0),
                              (('Unnamed: 5_level_0', '+/-'), 0.0),
                              (('Unnamed: 6_level_0', 'PIM'), 0),
                              (('Goals', 'EV'), 0),
                              (('Goals', 'PP'), 0),
                              (('Goals', 'SH'), 0),
                              (('Goals', 'GW'), 0.0),
                              (('Assists', 'EV'), 0.0),
                              (('Assists', 'PP'), 0.0),
                              (('Assists', 'SH'), 0.0),
                              (('Unnamed: 14_level_0', 'S'), 1),
                              (('Unnamed: 15_level_0', 'S%'), 0.0),
                              (('Unnamed: 16_level_0', 'SHFT'), 23.0),
                              (('Unnamed: 17_level_0', 'TOI'), '16:57')],
 '201810030TOR_TOR_goalies': [(('Unnamed: 0_level_0', 'Rk'), 1),
                              (('Unnamed: 1_level_0', 'Player'), 'Frederik Andersen'),
                              (('Unnamed: 2_level_0', 'DEC'), 'W'),
                              (('Goalie Stats', 'GA'), 2),
                              (('Goalie Stats', 'SA'), 36),
                              (('Goalie Stats', 'SV'), 34),
                              (('Goalie Stats', 'SV%'), 0.9440000000000001),
                              (('Goalie Stats', 'SO'), 0),
                              (('Unnamed: 8_level_0', 'PIM'), 0),
                              (('Unnamed: 9_level_0', 'TOI'), '61:01')],
 '201810030TOR_MTL_adv': [('Player', 'Joel Armia'),
                          ('iCF', 3.0),
                          ('SAT‑F', 14),
                          ('SAT‑A', 10),
                          ('CF%', 58.3),
                          ('CRel%', 1.3),
                          ('ZSO', 4.0),
                          ('ZSD', 1.0),
                          ('oZS%', 80.0),
                          ('HIT', 3),
                          ('BLK', 1.0)],
 '201810030TOR_TOR_adv': [('Player', 'Connor Brown'),
                          ('iCF', 2.0),
                          ('SAT‑F', 14),
                          ('SAT‑A', 12),
                          ('CF%', 53.8),
                          ('CRel%', 14.5),
                          ('ZSO', 2.0),
                          ('ZSD', 6.0),
                          ('oZS%', 25.0),
                          ('HIT', 0),
                          ('BLK', 1.0)]}"""
